name: Build and Test
permissions:
  contents: read
on: [push, pull_request]

jobs:
  build:
    name: Build
    if: >-
      ${{
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' &&
      github.event.pull_request.head.repo.full_name != '1Password/connect-sdk-go')
      }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -cover
